version: '3.8'

services:
  selenium-tests:
    build: .
    environment:
      - HEADLESS=true
      - BROWSER=chrome
      - WINDOW_SIZE=1920,1080
      - CI=true
      - DB_DISABLED=true
      # Application URL
      - APP_URL=http://98.80.5.203/
      # Point tests at Selenium Grid (standalone) inside the compose network
      - REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - ./reports/test_results:/app/reports/test_results:rw
    networks:
      - selenium-network

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "4444:4444"
    networks:
      - selenium-network

# Note: The 'mysql' and 'web-app' services have been removed.

networks:
  selenium-network:
    driver: bridge