name: Selenium Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests with docker-compose
        run: |
          docker-compose down -v || true
          docker-compose up --build --abort-on-container-exit || EXIT_CODE=$?
          echo "EXIT_CODE=${EXIT_CODE:-0}" >> $GITHUB_ENV

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test/test_results/**

      - name: Fail if tests failed
        run: |
          if [ "$EXIT_CODE" != "0" ]; then
            exit 1
          fi

